config/routes.rb
Rails.application.routes.draw do
  resources :books do
    member do
      get :delete
    end
  end
  root "books#index"
  
  #match 'about', to: "books#about", via: :get

  # get 'main/index'
  # get 'books/index'
  # get 'books/new'
  # get 'books/edit'
  # get 'books/show'
  # get 'books/destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @created_by = "Kirk"
    @books = Book.all
  end

  # def about
  #   @created_by = "Kirk"
  # end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: 'Book was successfully created.'
    else
      render 'new'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path, notice: 'Book was successfully updated.'
    else
      render 'edit' 
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = 'Book was successfully deleted.'
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(
      :title,
      :author,
      :price,
      :published_date
    )
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/books/_form.html.erb
<table class="table" summary="Book form"">
    <tr>
        <th>Title</th>
        <td><%= f.text_field(:title) %></td>
    </tr>
</table>

app/views/books/delete.html.erb
<h1>Delete a Book</h1>
</br>
<div class="books delete">

  <%= form_for(@book, method: 'delete') do |f|%>
    <p>Are you sure you want to permenantly delete this book?</p>
    
    <p class="book_title"><%= @book.title %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Book")%>
    </div>
  <% end %>
</div>

<div>
  <%= link_to "Back to Home", books_path, class: "button" %>
</div>

app/views/books/edit.html.erb
<h1>Update a Book</h1>

<div class="books edit">
  <h2>Edit Book</h2>
  <%= form_for(@book) do |f| %>

    <%= render 'form', f: f %>

    <div class="form-buttons">
      <%= f.submit("Edit Book")%>
    </div>

  <% end %>
</div>

<div>
  <%= link_to "Back to Home", books_path, class: "button" %>
</div>

app/views/books/index.html.erb
<h1>Home</h1>
<p>Created by <%= @created_by %> and styled with ChatGPT</p>

<!-- app/views/books/index.html.erb -->
<% if flash[:notice] %>
  <div class="flash-notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<h1>All Books</h1>

<table class="table" summary="Book list" style="width: 100%;">
  <thead>
    <tr>
      <th style="border: 1px solid;">Title</th>
      <th style="border: 1px solid;" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr style="border: 1px solid;">
        <td><%= book.title %></td>
        <td><%= link_to 'Show', book, class: "action_button" %></td>
        <td><%= link_to 'Edit', edit_book_path(book), class: "action_button" %></td>
        <td><%= link_to 'Delete', delete_book_path(book), class: "action_button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to "Add Book", new_book_path, class: "button" %>
</div>

app/views/books/new.html.erb
<h1>Add a Book</h1>

<div class="books new">
  <h2>New Book</h2>
  <%= form_for(@book) do |f| %>
    
    <%= render 'form', f: f %>

    <div class="form-buttons">
    <%= f.submit("Create Book")%>
    </div>

  <% end %>
</div>

<div>
  <%= link_to "Back to Home", books_path, class: "button" %>
</div>

app/views/books/show.html.erb
<h1>Show Details</h1>

<table class="table" summary="Book form"">
    <tbody>
    <tr>
        <th>Title</th>
        <td><%= @book.title %></td>
    </tr>
    </tbody>
</table>

<div>
  <%= link_to "Edit Book", edit_book_path(@book), class: "action_button" %>
  <%= link_to "Delete Book", delete_book_path(@book), class: "action_button" %>
  </br></br>
  <%= link_to "Back to Home", books_path, class: "button" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCollection</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Hello World! This is a test page!<p>